export const FETCH_POSTS_START = 'FETCH_POSTS_START'
export const FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR'
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS'

export const FETCH_POST_START = 'FETCH_POST_START'
export const FETCH_POST_ERROR = 'FETCH_POST_ERROR'
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS'
export const RESET_POST_DETAIL = 'RESET_POST_DETAIL'

export const FETCH_COMMENTS_START = 'FETCH_COMMENTS_START'
export const FETCH_COMMENTS_ERROR = 'FETCH_COMMENTS_ERROR'
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS'

export const CREATE_POST = 'CREATE_POST'
export const SET_IMAGE_URL ='SET_IMAGE_URL'

export const CREATE_COMMENT = 'CREATE_COMMENT'
export const RESET_CREATE_COMMENT= 'RESET_CREATE_COMMENT'

