export const LOGIN_START = 'LOGIN_START'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const LOGOUT = 'LOGOUT'

export const REGISTER_START = 'REGISTER_START'
export const REGISTER_ERROR = 'REGISTER_ERROR'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'

export const RESET = 'RESET'
export const RESET_PROFILE = 'RESET_PROFILE'
export const FETCH_PROFILE_START = 'FETCH_PROFILE_START'
export const FETCH_PROFILE_ERROR = 'FETCH_PROFILE_ERROR'
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS'

export const EDIT_PROFILE_START = 'EDIT_PROFILE_START'
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS'
export const EDIT_PROFILE_ERROR = 'EDIT_PROFILE_ERROR'
export const RESET_EDIT_PROFILE = 'EDIT_PROFILE_RESET'


export const FETCH_POSTS_START = 'FETCH_POSTS_START'
export const FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR'
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS'

export const FETCH_POST_START = 'FETCH_POST_START'
export const FETCH_POST_ERROR = 'FETCH_POST_ERROR'
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS'
export const RESET_POST_DETAIL = 'RESET_POST_DETAIL'

export const FETCH_COMMENTS_START = 'FETCH_COMMENTS_START'
export const FETCH_COMMENTS_ERROR = 'FETCH_COMMENTS_ERROR'
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS'
export const RESET_COMMENTS  = 'RESET_COMMENTS'

export const CREATE_POST_START = 'CREATE_POST'
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS '
export const CREATE_POST_ERROR = 'CREATE_POST_ERROR'
export const CREATE_POST_RESET = 'CREATE_POST_RESET'



export const CREATE_COMMENT = 'CREATE_COMMENT'
export const RESET_CREATE_COMMENT= 'RESET_CREATE_COMMENT'

